<a href="https://colab.research.google.com/github/nhareesha/MLAI/blob/main/NN/Tensorflow_lowlevel_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# Creating basic tensors
scalar = tf.constant(5)
# Tensor properties
print(scalar.shape)  # Shape
print(scalar.dtype)  # Data type

vector = tf.constant([1, 2, 3]) # vectore
# Tensor properties
print(vector.shape)  # Shape
print(vector.dtype)  # Data type

matrix = tf.constant([[1, 2], [3, 4]])
# Tensor properties
print(matrix.shape)  # Shape
print(matrix.dtype)  # Data type

matrix3d = tf.constant([[[1, 2, 3], [3, 4, 4]], [[11, 32, 33], [13, 34,34]]])
# Tensor properties
print(matrix3d.shape)  # Shape
print(matrix3d.dtype)  # Data type

()
<dtype: 'int32'>
(3,)
<dtype: 'int32'>
(2, 2)
<dtype: 'int32'>
(2, 2, 3)
<dtype: 'int32'>


# Basic Operation - Tensor Low level

In [3]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Addtion Element wise
add_result = tf.add(a, b)
print(add_result)

# Multiplication Element wise
multiplication_result = tf.multiply(a, b) # Vector
print(multiplication_result) # Vector


# Matrix operations
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
matrix_mult = tf.matmul(matrix_a, matrix_b)
print(matrix_mult) # Matrix



tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Variable Creation and Management

In [4]:
# Creating trainable variables

weight = tf.Variable(tf.random.normal([3,3]), name = 'weight') # 2 by 2 matrix

bias = tf.Variable(tf.zeros([3]), name = 'bias') # Vector

print(weight)
print(bias)



# Variable operations
weight.assign(tf.ones([3, 3]))  # Direct assignment

print(weight)
print(bias)

weight.assign_add(tf.ones([3, 3]))  # Incremental update

print(weight)
print(bias)

<tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.3063682 , -0.8999266 ,  0.9155995 ],
       [ 0.8136504 , -0.01450668, -0.32933256],
       [ 0.5656933 , -0.33271763,  0.03785708]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>
<tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>
<tf.Variable 'weight:0' shape=(3, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>


In [5]:
weight = tf.Variable(tf.random.uniform([3, 3]), name = "hello")

print(weight)

<tf.Variable 'hello:0' shape=(3, 3) dtype=float32, numpy=
array([[0.5956855 , 0.41738212, 0.03541696],
       [0.32384956, 0.88524175, 0.12071586],
       [0.04110122, 0.6383003 , 0.07538295]], dtype=float32)>


 ### TensorFlow requires the use of `tf.custom_gradient` decorator to define custom gradients.


 `@tf.custom_gradient decorator`. It knows that:

- The first element is the output tensor.
- The second element is the gradient function used for backpropagation.( callable that defines the gradient.)


- If` y `is the final output used in a loss function, then `incoming_grad` is often 1 (scalar) when computing the gradient of the loss with respect to y.
- If `y` is part of a larger computation graph, `incoming_grad` will be the gradient of the subsequent operations with respect to y.

In [15]:
# Custom Gradient computation

@tf.custom_gradient
def custom_operation(x):

  def grad(incoming_grad):
    print(incoming_grad)
    return incoming_grad * 2.0 * x # Define the custom gradient

  return x * x, grad


# Example usage
X = tf.Variable(tf.random.normal([3, 2]), name = "X")

print(X)

# Records the operations on varaible during forward pass
with tf.GradientTape() as tape:
  tape.watch(X)
  y = custom_operation(X)

# Calculated gradiets wrt to loss function (y)
gradient = tape.gradient(y, X)
print(gradient)

<tf.Variable 'X:0' shape=(3, 2) dtype=float32, numpy=
array([[-2.4422212 , -0.83448416],
       [ 1.7488308 ,  0.24138296],
       [-0.740779  , -0.60193884]], dtype=float32)>
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-4.8844423 -1.6689683]
 [ 3.4976616  0.4827659]
 [-1.481558  -1.2038777]], shape=(3, 2), dtype=float32)


## Tensor Manipulation

In [23]:
tensor = tf.constant([[1, 2],[3, 4]])

print(tensor)

reshaped = tf.reshape(tensor, [4])

print(reshaped)

# Casting
float_tensor = tf.cast(tensor, tf.float32)

# Slicing
sliced = tensor[0:1, :] # first row and all columns

print(sliced)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([[1]], shape=(1, 1), dtype=int32)


## Memory Management


`tf.random.normal([1000, 1000])`: This operation creates a `1000x1000` matrix of random values drawn from a normal distribution, and it is **explicitly placed on the GPU**.

In [ ]:
# Explicit memory management
with tf.device('/GPU:0'):
    gpu_tensor = tf.random.normal([1000, 1000])

# Memory clearing
tf.keras.backend.clear_session()